### ISSUE TITLE
TypeError: read_feather() got an unexpected keyword argument 'types_mapper'

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#6414]
`read_feather` does not work with pyarrow<11.0
