### ISSUE TITLE
AttributeError: module 'pyarrow' has no attribute 'parquet'

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#951]
### Describe the problem

Test failure with #950, but unrelated to that code change. 

### Source code / logs

Fix:

Instead of:

```python
import pyarrow as pa
pa.parquet
```

Do:
```python
import pyarrow.parquet as pq
```
Offending line:
https://github.com/modin-project/modin/blob/master/modin/pandas/test/test_io.py#L83

**Comment by Patel-Aakash** [comment]
But why??

**Comment by dliu-fn** [comment]
Allow me to clarify: "But WHY?!"

Joking aside, why on God's green earth is `pa.parquet` an invalid library path, but `import pyarrow.parquet as pq` works fine when the only visible difference is an alias change? Is there some kind of overlapping alias that override the default `pa` alias?

**Comment by anmyachev** [comment]
According to https://github.com/apache/arrow/blob/3ad2d0ccd98192d32d54af371bad6b61ea3c4736/python/pyarrow/__init__.py#L140-L142 `.parquet` - it is considered as an optional submodule, respectively, the import of the root module is made in such a way as not to import optional submodules.
