### PR TITLE
FIX-#6414: fix 'read_feather' with pyarrow<11.0

### LINKED ISSUE #6414: TypeError: read_feather() got an unexpected keyword argument 'types_mapper'
`read_feather` does not work with pyarrow<11.0

### PR DESCRIPTION
**Pull request by anmyachev**
## What do these changes do?

The changes tested in https://github.com/modin-project/modin/pull/6413 with `pyarrow==7.0.0`.

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #6414 
- [x] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

File: modin/core/storage_formats/pandas/parsers.py [hunk 1]
```diff
@@ -891,7 +891,12 @@ def parse(fname, **kwargs):
             fname,
             **(kwargs.pop("storage_options", None) or {}),
         ) as file:
-            df = feather.read_feather(file, **kwargs, **to_pandas_kwargs)
+            if not to_pandas_kwargs:
+                df = feather.read_feather(file, **kwargs)
+            else:
+                # `read_feather` doesn't accept `types_mapper` if pyarrow<11.0
+                pa_table = feather.read_table(file, **kwargs)
+                df = pa_table.to_pandas(**to_pandas_kwargs)
```
[the remark this answers is not in the document]
Comment (YarShev) [reply modin/core/storage_formats/pandas/parsers.py:899]: Should we put a comment here that we follow pandas semantics?

[the remark this answers is not in the document]
Comment (anmyachev) [reply modin/core/storage_formats/pandas/parsers.py]: @YarShev added

**Review by YarShev — APPROVED** [review]
