### ISSUE TITLE
Add support for `apply` function that accesses `pd.DataFrame` or `pd.Series`

### ISSUE THREAD

**Issue by bundasht** [modin-project/modin#2014]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 20.04
- **Modin version** (`modin.__version__`):
0.8.0, Ray version 0.8.6, pandas version 1.0.5
- **Python version**:
3.8.5, Anaconda, Jupyter Lab
- **Code we can use to reproduce**:
Not really reproduable, but: 

```python
def days_filter(data):
    data_hash = pd.DataFrame(data).iloc[0]['hash']
    data = data[(data.day < last_conversion_days.loc[data_hash].day) & (data.day > (last_conversion_days.loc[data_hash].day - pd.Timedelta(days=30)))]
    return data
```

```python
t = convs.groupby('hash').apply(days_filter)
t
```

### Describe the problem
When I am using groupby + apply with modin.pandas I am getting error:

```
RayTaskError(RecursionError): ray::modin.engines.ray.pandas_on_ray.frame.partition.deploy_ray_func() (pid=13325, ip=192.168.0.10)
  File "python/ray/_raylet.pyx", line 410, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task
ray.exceptions.RayTaskError: ray::modin.engines.ray.pandas_on_ray.frame.axis_partition.deploy_ray_func() (pid=13325, ip=192.168.0.10)
  File "/home/bundash/anaconda3/envs/ml/lib/python3.8/site-packages/modin/pandas/dataframe.py", line 2486, in __getattr__
    return object.__getattribute__(self, key)
AttributeError: 'DataFrame' object has no attribute '_query_compiler'
```

I saw that similar problems can be encountered during serialization, but I am not using any parallelization code here (besides modin itself). 

Modin was imported with: 
```python
import os
os.environ["MODIN_ENGINE"] = "ray"  # Modin will use Ray
import modin.pandas as pd
```

No additional ray or modin configuration was done

### Source code / logs
Full stacktrace:

```
UserWarning: `DataFrame.__getstate__` defaulting to pandas implementation.
---------------------------------------------------------------------------
RayTaskError(RecursionError)              Traceback (most recent call last)
<ipython-input-9-4939df74092a> in <module>
----> 1 t = convs.groupby('hash').apply(days_filter)
      2 t

~/anaconda3/envs/ml/lib/python3.8/site-packages/modin/pandas/groupby.py in apply(self, func, *args, **kwargs)
    258 
    259     def apply(self, func, *args, **kwargs):
--> 260         return self._apply_agg_function(
    261             # Grouping column in never dropped in groupby.apply, so drop=False
    262             lambda df: df.apply(func, *args, **kwargs),

~/anaconda3/envs/ml/lib/python3.8/site-packages/modin/pandas/groupby.py in _apply_agg_function(self, f, drop, *args, **kwargs)
    661         else:
    662             groupby_qc = self._query_compiler
--> 663         new_manager = groupby_qc.groupby_agg(
    664             by, self._axis, f, self._kwargs, kwargs, drop=self._drop
    665         )

~/anaconda3/envs/ml/lib/python3.8/site-packages/modin/backends/pandas/query_compiler.py in groupby_agg(self, by, axis, agg_func, groupby_args, agg_args, drop)
   2065                 return compute_groupby(df.copy())
   2066 
-> 2067         new_modin_frame = self._modin_frame._apply_full_axis(
   2068             axis, lambda df: groupby_agg_builder(df)
   2069         )

~/anaconda3/envs/ml/lib/python3.8/site-packages/modin/engines/base/frame/data.py in _apply_full_axis(self, axis, func, new_index, new_columns, dtypes)
   1206         # Index objects for new object creation. This is shorter than if..else
   1207         if new_columns is None:
-> 1208             new_columns = self._frame_mgr_cls.get_indices(
   1209                 1, new_partitions, lambda df: df.columns
   1210             )

~/anaconda3/envs/ml/lib/python3.8/site-packages/modin/engines/ray/pandas_on_ray/frame/partition_manager.py in get_indices(cls, axis, partitions, index_func)
     92                 else []
     93             )
---> 94         new_idx = ray.get(new_idx)
     95         return new_idx[0].append(new_idx[1:]) if len(new_idx) else new_idx
     96 

~/anaconda3/envs/ml/lib/python3.8/site-packages/ray/worker.py in get(object_ids, timeout)
   1472                     worker.core_worker.dump_object_store_memory_usage()
   1473                 if isinstance(value, RayTaskError):
-> 1474                     raise value.as_instanceof_cause()
   1475                 else:
   1476                     raise value

RayTaskError(RecursionError): ray::modin.engines.ray.pandas_on_ray.frame.partition.deploy_ray_func() (pid=13325, ip=192.168.0.10)
  File "python/ray/_raylet.pyx", line 410, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task
ray.exceptions.RayTaskError: ray::modin.engines.ray.pandas_on_ray.frame.axis_partition.deploy_ray_func() (pid=13325, ip=192.168.0.10)
  File "/home/bundash/anaconda3/envs/ml/lib/python3.8/site-packages/modin/pandas/dataframe.py", line 2486, in __getattr__
    return object.__getattribute__(self, key)
AttributeError: 'DataFrame' object has no attribute '_query_compiler'
```

**Comment by devin-petersohn** [comment]
@Bodya00 Thanks for posting the issue! This was a bit of a complicated one.

I figured out the issue, it is related to the `pd.DataFrame` in the code. We will certainly figure out how to fix this, but a small rewrite will fix your issue in the meantime.

```python
def days_filter(data): 
    data_hash = data.iloc[0]['hash']
    data = data[
        (data.day < last_conversion_days.loc[data_hash].day) & 
        (data.day > (last_conversion_days.loc[data_hash].day - pd.Timedelta(days=30)))
    ]
    return data

t = convs.groupby('hash').apply(days_filter)
t
```
Let me know if this helps!

**Comment by Bodya00** [comment]
Wow, thank you for spending time on this. 
Thank you.

**Comment by vnlitvinov** [comment]
I'm pretty sure it's caused by #672, which I'm aiming to close with #2835, so, when it lands, we can re-check if your case is still exhibiting the exception.

**Comment by vnlitvinov** [comment]
@bundasht fixing PR has landed, if you could check your code using [lastest master](https://modin.readthedocs.io/en/latest/installation.html#installing-from-the-github-master-branch) it would be awesome.

**Comment by devin-petersohn** [comment]
@bundasht @vnlitvinov I am going to close this as resolved by #2835. Please reopen if the issue still exists!
