### PR TITLE
Do not always require pyarrow

### LINKED ISSUE #2090: Fresh install requires pyarrow and pyarrow.gandiva
This code is run to cause this requirement:

https://github.com/modin-project/modin/blob/90adc7d7cbbb424c27f0618b94cb006af06dc5e7/modin/backends/pyarrow/query_compiler.py#L20-L21

This is not in the `setup.py` requirements, but I don't think we should add it. We should probably just wrap that in a conditional.

### PR DESCRIPTION
**Pull request by vnlitvinov**
Signed-off-by: Vasilij Litvinov <vasilij.n.litvinov@intel.com>

## What do these changes do?
Relax requirements on having `pyarrow` installed.
After these changes if there is `pyarrow` is only required to have `modin.backends.PyarrowQueryCompiler`, base and Pandas backends always exist.

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #2090 
- [ ] tests added and passing

### CODE REVIEW

File: modin/backends/__init__.py [hunk 1]
```diff
@@ -13,6 +13,11 @@
 
 from .base import BaseQueryCompiler
 from .pandas import PandasQueryCompiler
-from .pyarrow import PyarrowQueryCompiler
 
-__all__ = ["BaseQueryCompiler", "PandasQueryCompiler", "PyarrowQueryCompiler"]
+__all__ = ["BaseQueryCompiler", "PandasQueryCompiler"]
+try:
```
Comment (dchigarev) [inline modin/backends/__init__.py:18]: What will happen if we **want** to import `PyarrowQueryCompiler`, but don't have installed pyarrow?
I mean how informing  and explaining error will be?

Comment (vnlitvinov) [reply modin/backends/__init__.py:18]: That depends on how you import `PyarrowQueryCompiler`.

Simple `from modin.backends import PyarrowQueryCompiler` would yield `ImportError: cannot import name 'PyarrowQueryCompiler' from 'modin.backends'`, and I think that the error would make developer look into `modin.backends` and he/she would see this `try..except` pattern and then would manually try to do `from modin.backends.pyarrow import PyarrowQueryCompiler` and _then_ would see `cannot import pyarrow`.

So solving the issue would take them one more step compared to empty init, yes, but I think having simpler imports is worth it.

Comment (vnlitvinov) [reply modin/backends/__init__.py:18]: We would be able to do lazy submodule imports (which would retain the benefit of simpler imports _and_ emit errors about `pyarrow` at the same time) when we bump our minimal version to 3.7: https://www.python.org/dev/peps/pep-0562/

**Review by dchigarev — APPROVED** [review]
